// Dados gerados no chatgpt
export const httpErrorsExplanation = [
  { code: 100, description: "Continue", explanation: "Indica que a parte inicial de uma requisição foi recebida e o cliente deve continuar com a requisição." },
  { code: 101, description: "Switching Protocols", explanation: "Indica que o servidor está mudando os protocolos conforme solicitado pelo cliente." },
  { code: 102, description: "Processing", explanation: "Indica que o servidor recebeu e está processando a requisição, mas ainda não está pronto para retornar uma resposta." },
  { code: 103, description: "Early Hints", explanation: "A resposta de informação HTTP 103 Early Hints pode ser enviada por um servidor enquanto ele ainda está preparando uma resposta, com dicas sobre os recursos que o servidor espera que a resposta final vincule. Isso permite que um navegador comece a pré-carregar recursos antes mesmo de o servidor ter preparado e enviado a resposta final." },
  { code: 200, description: "OK", explanation: "A requisição foi bem-sucedida." },
  { code: 201, description: "Created", explanation: "A requisição foi bem-sucedida e um novo recurso foi criado." },
  { code: 202, description: "Accepted", explanation: "A requisição foi aceita para processamento, mas ainda não foi concluída." },
  { code: 203, description: "Non-Authoritative Information", explanation: "O servidor está retornando informações que não são do servidor original." },
  { code: 204, description: "No Content", explanation: "A requisição foi bem-sucedida, mas não há conteúdo para retornar." },
  { code: 205, description: "Reset Content", explanation: "O servidor solicita que o cliente limpe a vista de entrada para a requisição." },
  { code: 206, description: "Partial Content", explanation: "O servidor está retornando apenas uma parte do recurso, conforme solicitado." },
  { code: 207, description: "Multi-Status", explanation: "O corpo da resposta contém informações sobre múltiplos recursos." },
  { code: 208, description: "Already Reported", explanation: "Indica que a coleção de recursos foi já reportada em uma resposta anterior." },
  { code: 214, description: "Transformation Applied", explanation: "A Transformação HTTP 214 Aplicada é um código de status não oficial usado em combinação com o cabeçalho HTTP Warning e incluído com mensagens de resposta HTTP para indicar que uma transformação foi aplicada à representação." },
  { code: 226, description: "IM Used", explanation: "O servidor já aplicou um ou mais transformações no recurso." },
  { code: 300, description: "Multiple Choices", explanation: "A requisição tem várias opções de resposta." },
  { code: 301, description: "Moved Permanently", explanation: "O recurso solicitado foi movido permanentemente para uma nova URL." },
  { code: 302, description: "Found", explanation: "O recurso solicitado foi encontrado, mas está temporariamente em outra URL." },
  { code: 303, description: "See Other", explanation: "O cliente deve acessar o recurso em outra URL." },
  { code: 304, description: "Not Modified", explanation: "O recurso não foi modificado desde a última requisição." },
  { code: 305, description: "Use Proxy", explanation: "O recurso deve ser acessado através de um proxy." },
  { code: 307, description: "Temporary Redirect", explanation: "O recurso está temporariamente em uma URL diferente." },
  { code: 308, description: "Permanent Redirect", explanation: "O recurso foi movido permanentemente para uma nova URL." },
  { code: 400, description: "Bad Request", explanation: "A requisição não pôde ser entendida pelo servidor devido a uma sintaxe inválida." },
  { code: 401, description: "Unauthorized", explanation: "A requisição requer autenticação do usuário." },
  { code: 402, description: "Payment Required", explanation: "A requisição não foi processada porque requer pagamento." },
  { code: 403, description: "Forbidden", explanation: "O servidor entendeu a requisição, mas se recusa a autorizá-la." },
  { code: 404, description: "Not Found", explanation: "O recurso solicitado não foi encontrado no servidor." },
  { code: 405, description: "Method Not Allowed", explanation: "O método especificado na requisição não é permitido para o recurso solicitado." },
  { code: 406, description: "Not Acceptable", explanation: "O recurso solicitado é capaz de gerar conteúdo apenas em formatos que não são aceitáveis." },
  { code: 407, description: "Proxy Authentication Required", explanation: "O cliente deve se autenticar com o proxy." },
  { code: 408, description: "Request Timeout", explanation: "O servidor não recebeu a requisição no tempo esperado." },
  { code: 409, description: "Conflict", explanation: "A requisição não pôde ser concluída devido a um conflito com o estado atual do recurso." },
  { code: 410, description: "Gone", explanation: "O recurso solicitado foi removido e não está mais disponível." },
  { code: 411, description: "Length Required", explanation: "A requisição não possui um cabeçalho 'Content-Length' necessário." },
  { code: 412, description: "Precondition Failed", explanation: "Uma condição especificada na requisição falhou." },
  { code: 413, description: "Payload Too Large", explanation: "O corpo da requisição é maior do que o servidor está disposto ou capaz de processar." },
  { code: 414, description: "URI Too Long", explanation: "O URI fornecido foi muito longo para o servidor processar." },
  { code: 415, description: "Unsupported Media Type", explanation: "O tipo de mídia do recurso solicitado não é suportado." },
  { code: 416, description: "Range Not Satisfiable", explanation: "O servidor não pode fornecer a parte do recurso solicitada." },
  { code: 417, description: "Expectation Failed", explanation: "O servidor não pode atender à expectativa especificada no cabeçalho da requisição." },
  { code: 418, description: "I’m a teapot", explanation: "O código de resposta de erro HTTP 418 I'm a teapot client indica que o servidor se recusa a preparar café porque ele é, permanentemente, um bule de chá." },
  { code: 420, description: "Enhance Your Calm", explanation: "O código de status de resposta HTTP 420 Method Failure e 420 Enhance your calm é um código de status HTTP não oficial que é retornado pelo servidor para indicar um erro do cliente." },
  { code: 421, description: "Misdirected Request", explanation: "A requisição foi direcionada para um servidor que não é capaz de produzir uma resposta." },
  { code: 422, description: "Unprocessable Entity", explanation: "O servidor entende o conteúdo da requisição, mas não pode processá-lo." },
  { code: 423, description: "Locked", explanation: "O recurso solicitado está bloqueado." },
  { code: 424, description: "Failed Dependency", explanation: "A requisição falhou devido a uma falha em uma requisição anterior." },
  { code: 425, description: "Too Early", explanation: "O código de status de resposta HTTP 425 Too Early indica que o servidor não está disposto a correr o risco de processar uma solicitação que pode ser repetida, o que cria o potencial para um ataque de repetição." },
  { code: 426, description: "Upgrade Required", explanation: "O cliente deve mudar para um protocolo diferente." },
  { code: 428, description: "Precondition Required", explanation: "O servidor requer que a requisição seja condicional." },
  { code: 429, description: "Too Many Requests", explanation: "O usuário enviou muitas requisições em um determinado período." },
  { code: 431, description: "Request Header Fields Too Large", explanation: "Os campos do cabeçalho da requisição são muito grandes." },
  { code: 444, description: "No Response", explanation: "O código de status de resposta HTTP 444 No Response é um código de status HTTP não oficial específico para nginx e indica que a conexão HTTP está fechada. Nenhuma informação, nem mesmo este código de status, é enviada ao cliente." },
  { code: 450, description: "Blocked by Windows Parental Controls", explanation: "O código de status de resposta HTTP 450 Bloqueado pelos Controles Parentais do Windows é um código de status HTTP não oficial específico da Microsoft e retornado pelo servidor para indicar que os controles parentais estão ativados e bloqueando o acesso ao recurso solicitado." },
  { code: 451, description: "Unavailable For Legal Reasons", explanation: "O recurso não está disponível por razões legais." },
  { code: 497, description: "HTTP Request Sent to HTTPS Port", explanation: "O código de status de resposta HTTP 497 Solicitação HTTP enviada para porta HTTPS é um código de status HTTP não oficial específico do nginx e é retornado pelo servidor para indicar que uma solicitação HTTP regular foi enviada para a porta HTTPS." },
  { code: 498, description: "Token expired/invalid", explanation: "A resposta HTTP 498 Token inválido é um código de status HTTP não oficial específico do ArcGIS e indica que a solicitação HTTP incluiu um token, mas ele não foi aceito." },
  { code: 499, description: "Client Closed Request", explanation: "O código de status de resposta HTTP 499 é um código de status HTTP não oficial específico para ArcGIS com 499 Token Required e nginx com 499 Client Closed Request." },
  { code: 500, description: "Internal Server Error", explanation: "O servidor encontrou uma condição inesperada." },
  { code: 501, description: "Not Implemented", explanation: "O servidor não suporta a funcionalidade necessária para atender à requisição." },
  { code: 502, description: "Bad Gateway", explanation: "O servidor recebeu uma resposta inválida ao tentar atender a requisição." },
  { code: 503, description: "Service Unavailable", explanation: "O servidor está temporariamente incapaz de processar a requisição." },
  { code: 504, description: "Gateway Timeout", explanation: "O servidor atuou como um gateway e não recebeu uma resposta a tempo." },
  { code: 506, description: "Variant Also Negotiates", explanation: "O código de status de resposta HTTP 506 Variant Also Negotiates pode ser fornecido no contexto de Negociação de Conteúdo Transparente (consulte RFC 2295)." },
  { code: 507, description: "Insufficient Storage", explanation: "O código de status de resposta HTTP 507 Armazenamento Insuficiente pode ser fornecido no contexto do protocolo WebDAV (consulte RFC 4918)." },
  { code: 508, description: "Loop Detected", explanation: "O código de status de resposta HTTP 508 Loop Detectado pode ser fornecido no contexto do protocolo WebDAV." },
  { code: 509, description: "Bandwidth Limit Exceeded", explanation: "O código de status de resposta HTTP 509 Limite de largura de banda excedido é um código de status HTTP não oficial específico do Apache Web Server e do cPanel que indica que o cliente de hospedagem web excedeu a cota de largura de banda no lado do servidor." },
  { code: 510, description: "Not Extended", explanation: "O código de status de resposta HTTP 510 Not Extended é enviado no contexto do HTTP Extension Framework, definido no RFC 2774." },
  { code: 511, description: "Network Authentication Required", explanation: "O cliente precisa se autenticar para acessar a rede." },
  { code: 521, description: "Web Server Is Down", explanation: "O código de status de resposta HTTP 521 Web Server Is Down é um código de status HTTP não oficial específico do Cloudflare." },
  { code: 522, description: "Connection Timed Out", explanation: "O código de status de resposta HTTP 522 é um código de status HTTP não oficial específico do Cloudflare." },
  { code: 523, description: "Origin Is Unreachable", explanation: "O código de status de resposta HTTP 523 Origin Is Unreachable é um código de status HTTP não oficial específico do Cloudflare." },
  { code: 525, description: "SSL Handshake Failed", explanation: "O código de status de resposta HTTP 525 SSL Handshake Failed é um código de status HTTP não oficial específico do Cloudflare." },
  { code: 530, description: "Site Frozen", explanation: "O código de status de resposta HTTP 530 Site Frozen é um código de status HTTP não oficial específico do Cloudflare e do Pantheon." },
  { code: 599, description: "Network Connect Timeout Error", explanation: "O código de status de resposta HTTP 599 Erro de tempo limite de conexão de rede é um código de status HTTP não oficial usado por alguns proxies para sinalizar um tempo limite de conexão de rede atrás do proxy para um cliente na frente do proxy." },
];
